### ISSUE TITLE
Memory Probelm

### ISSUE THREAD

**Issue by fnmps** [weddige/miniball#1]
It seems that this module, when using something like this:

miniball.Miniball([val1, val2, val3, etc..]).squared_root()

Uses about 300KiB of memory and doesn't free it, after it finished running, which means when you are trying to do hundreds of thousands of iterations over it, the system will run out of memory and simply kill the process.

**Comment by weddige** [comment]
Tnx, I'll have a look at this as soon as possible.

**Comment by weddige** [comment]
This should be fixed with ed54fd500b5e99579ddda9b402938ee9bdf97189.
