### ISSUE TITLE
Arch Linux package

### ISSUE THREAD

**Issue by Pseudomanifold** [weddige/miniball#2]
Dear Konstantin,

thanks a lot for taking the time to create this package! Since I want to use it in my Linux distribution (Arch Linux), I decided to create a small package for it:

https://aur.archlinux.org/packages/python-miniball/

I would be happy if you could add this package to the README so that people know where to find the software.

Best,
  Bastian

**Comment by weddige** [comment]
Thank you. I updated the README.

**Comment by Pseudomanifold** [comment]
Thank you very much and best wishes for the new year!
