### ISSUE TITLE
installing miniball

### ISSUE THREAD

**Issue by HebatallaElnaggar** [weddige/miniball#4]
Hi,

I tried to install miniball by running setup.py. The installation goes with no errors but when I import miniball I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hebatalla/Downloads/miniball-master/miniball/__init__.py", line 2, in <module>
    import miniball.bindings
ModuleNotFoundError: No module named 'miniball.bindings'

**Comment by Minys233** [comment]
It's seems you are running  python in the installation directory.
Python will search current dir first when import a module, so check if you are running python console in the installation dir. If this module is successfully installed, files of this module will be moved into /some/path/site-packages directory, which holds every 3rd party packages installed.
