### ISSUE TITLE
BLD: consider releasing universal Python wheels ?

### ISSUE THREAD

**Issue by neutrinoceros** [weddige/miniball#7]
would it be possible to publish some wheels for all three major platforms (not just windows) on PyPI ?
It may be possible to avoid making one wheel per Python version using `Py_LIMITED_API`

For example see how this was done in casa-formats-io: https://github.com/radio-astro-tools/casa-formats-io/pull/50

**Comment by weddige** [comment]
Thank you for the suggestion. I'll have a look at it (as soon as I find some time, which might take a while).

**Comment by neutrinoceros** [comment]
looks like even building from source via pip is going to break at some point in the future

reproducer
```shell
python -m venv .venv
.venv/bin/activate
python -m pip install -U pip
python -m pip install miniballcpp --no-binary miniballcpp
```

ouptput
```
 DEPRECATION: miniballcpp is being installed using the legacy 'setup.py install' method,
 because it does not have a 'pyproject.toml' and the 'wheel' package is not installed.
 pip 23.1 will enforce this behaviour change.
 A possible replacement is to enable the '--use-pep517' option.
 Discussion can be found at https://github.com/pypa/pip/issues/8559
```
see https://github.com/pypa/pip/issues/8559

If you're interested, I should be able to help with modernizing the package to these uprising standards.

**Comment by weddige** [comment]
I managed to find a few minutes and added the pyproject.toml and some basic tests: https://github.com/weddige/miniball/pull/8

**Comment by neutrinoceros** [comment]
Awesome, thank you ! I'm still game to help you with wheels automation (using https://cibuildwheel.readthedocs.io/en/stable/) and/or `PY_LIMITED_API`, just let me know if you'd like a hand !

**Comment by weddige** [comment]
Thank you for the offer. I'll give it a try today and see how far I'll get. If there are issues still open after that, I'll thankfully take any PR.

**Comment by neutrinoceros** [comment]
Thanks a lot for your work on this !
